name: Test
on:
  push:
    branches: [ main ]
  pull_request:
  schedule:
    - cron: "0 0 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.22.x
    - name: Test
      run: go test -v ./... -coverprofile=profile.cov
    - name: Send coverage
      uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: profile.cov
    - name: Go vet
      run: go vet ./...
    - name: Gofmt
      run: |
        # gofmt always returns true, so we use grep '^' which returns
        # true on non-empty output, but will otherwise passthrough all
        # output lines.
        if gofmt -d -s . | grep '^'; then
          exit 1
        fi
    - name: Get goimports
      run: go install golang.org/x/tools/cmd/goimports@latest
    - name: Run Goimports
      run: |
        # goimports always returns true, so we use grep '^' which returns
        # true on non-empty output, but will otherwise passthrough all
        # output lines.
        #
        # goimports does not support "gofmt -s" so both goimports and gofmt are
        # required.
        find . -name "*.go" | egrep -v "pb.go$" | while read l; do
          if goimports -d $l | grep '^'; then
            exit 1;
          fi;
        done
    - name: Get revive
      run: go install github.com/mgechev/revive@latest
    - name: Run revive
      run: revive ./...
    - name: Get staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@latest
    - name: Run staticcheck
      run: staticcheck ./...
    - name: Build
      run: go build -v ./...
